List<Map<String, String>> countries = [
  {'name': 'Christmas Island', 'shortName': 'CX'},
  {'name': 'Eritrea', 'shortName': 'ER'},
  {'name': 'Samoa', 'shortName': 'WS'},
  {'name': 'North Macedonia', 'shortName': 'MK'},
  {'name': 'Djibouti', 'shortName': 'DJ'},
  {'name': 'Jordan', 'shortName': 'JO'},
  {'name': 'Pakistan', 'shortName': 'PK'},
  {'name': 'French Polynesia', 'shortName': 'PF'},
  {'name': 'Ireland', 'shortName': 'IE'},
  {'name': 'Mauritania', 'shortName': 'MR'},
  {'name': 'Denmark', 'shortName': 'DK'},
  {'name': 'Namibia', 'shortName': 'NA'},
  {'name': 'Ghana', 'shortName': 'GH'},
  {'name': 'South Sudan', 'shortName': 'SS'},
  {'name': 'Slovakia', 'shortName': 'SK'},
  {'name': 'American Samoa', 'shortName': 'AS'},
  {'name': 'Moldova', 'shortName': 'MD'},
  {'name': 'North Korea', 'shortName': 'KP'},
  {'name': 'Macau', 'shortName': 'MO'},
  {'name': 'Turks and Caicos Islands', 'shortName': 'TC'},
  {'name': 'Seychelles', 'shortName': 'SC'},
  {'name': 'Armenia', 'shortName': 'AM'},
  {'name': 'CuraÃ§ao', 'shortName': 'CW'},
  {'name': 'Guadeloupe', 'shortName': 'GP'},
  {'name': 'British Indian Ocean Territory', 'shortName': 'IO'},
  {'name': 'Equatorial Guinea', 'shortName': 'GQ'},
  {'name': 'Syria', 'shortName': 'SY'},
  {'name': 'Angola', 'shortName': 'AO'},
  {'name': 'Tajikistan', 'shortName': 'TJ'},
  {'name': 'Venezuela', 'shortName': 'VE'},
  {'name': 'United States Minor Outlying Islands', 'shortName': 'UM'},
  {'name': 'Ãland Islands', 'shortName': 'AX'},
  {'name': 'Poland', 'shortName': 'PL'},
  {'name': 'Saudi Arabia', 'shortName': 'SA'},
  {'name': 'Republic of the Congo', 'shortName': 'CG'},
  {'name': 'Bosnia and Herzegovina', 'shortName': 'BA'},
  {'name': 'United States Virgin Islands', 'shortName': 'VI'},
  {'name': 'New Caledonia', 'shortName': 'NC'},
  {'name': 'San Marino', 'shortName': 'SM'},
  {'name': 'Czechia', 'shortName': 'CZ'},
  {'name': 'Guatemala', 'shortName': 'GT'},
  {'name': 'South Korea', 'shortName': 'KR'},
  {'name': 'Estonia', 'shortName': 'EE'},
  {'name': 'Nepal', 'shortName': 'NP'},
  {'name': 'Kosovo', 'shortName': 'XK'},
  {'name': 'Botswana', 'shortName': 'BW'},
  {'name': 'Philippines', 'shortName': 'PH'},
  {'name': 'Saint Pierre and Miquelon', 'shortName': 'PM'},
  {'name': 'Iraq', 'shortName': 'IQ'},
  {'name': 'Lebanon', 'shortName': 'LB'},
  {'name': 'Burundi', 'shortName': 'BI'},
  {'name': 'Mongolia', 'shortName': 'MN'},
  {'name': 'Faroe Islands', 'shortName': 'FO'},
  {'name': 'Paraguay', 'shortName': 'PY'},
  {'name': 'Svalbard and Jan Mayen', 'shortName': 'SJ'},
  {'name': 'Tokelau', 'shortName': 'TK'},
  {'name': 'Guernsey', 'shortName': 'GG'},
  {'name': 'Caribbean Netherlands', 'shortName': 'BQ'},
  {'name': 'Algeria', 'shortName': 'DZ'},
  {'name': 'France', 'shortName': 'FR'},
  {'name': 'Netherlands', 'shortName': 'NL'},
  {'name': 'Greenland', 'shortName': 'GL'},
  {'name': 'Sint Maarten', 'shortName': 'SX'},
  {'name': 'Chad', 'shortName': 'TD'},
  {'name': 'Finland', 'shortName': 'FI'},
  {'name': 'Panama', 'shortName': 'PA'},
  {'name': 'Palestine', 'shortName': 'PS'},
  {'name': 'Yemen', 'shortName': 'YE'},
  {'name': 'Brazil', 'shortName': 'BR'},
  {'name': 'Nigeria', 'shortName': 'NG'},
  {'name': 'Palau', 'shortName': 'PW'},
  {'name': 'Japan', 'shortName': 'JP'},
  {'name': 'Tanzania', 'shortName': 'TZ'},
  {'name': 'Kazakhstan', 'shortName': 'KZ'},
  {'name': 'Portugal', 'shortName': 'PT'},
  {'name': 'South Georgia', 'shortName': 'GS'},
  {'name': 'Sri Lanka', 'shortName': 'LK'},
  {'name': 'Germany', 'shortName': 'DE'},
  {'name': 'Western Sahara', 'shortName': 'EH'},
  {'name': 'Myanmar', 'shortName': 'MM'},
  {'name': 'Colombia', 'shortName': 'CO'},
  {'name': 'Peru', 'shortName': 'PE'},
  {'name': 'Senegal', 'shortName': 'SN'},
  {'name': 'Kyrgyzstan', 'shortName': 'KG'},
  {'name': 'China', 'shortName': 'CN'},
  {'name': 'Afghanistan', 'shortName': 'AF'},
  {'name': 'Turkey', 'shortName': 'TR'},
  {'name': 'Liberia', 'shortName': 'LR'},
  {'name': 'South Africa', 'shortName': 'ZA'},
  {'name': 'Chile', 'shortName': 'CL'},
  {'name': 'Malta', 'shortName': 'MT'},
  {'name': 'Kiribati', 'shortName': 'KI'},
  {'name': 'Cape Verde', 'shortName': 'CV'},
  {'name': 'Jersey', 'shortName': 'JE'},
  {'name': 'Iceland', 'shortName': 'IS'},
  {'name': 'Gambia', 'shortName': 'GM'},
  {'name': 'Vanuatu', 'shortName': 'VU'},
  {'name': 'Uruguay', 'shortName': 'UY'},
  {'name': 'Oman', 'shortName': 'OM'},
  {'name': 'Sudan', 'shortName': 'SD'},
  {'name': 'India', 'shortName': 'IN'},
  {'name': 'Laos', 'shortName': 'LA'},
  {'name': 'Aruba', 'shortName': 'AW'},
  {'name': 'Martinique', 'shortName': 'MQ'},
  {'name': 'Comoros', 'shortName': 'KM'},
  {'name': 'Spain', 'shortName': 'ES'},
  {'name': 'Antigua and Barbuda', 'shortName': 'AG'},
  {'name': 'Uzbekistan', 'shortName': 'UZ'},
  {'name': 'Maldives', 'shortName': 'MV'},
  {'name': 'Gibraltar', 'shortName': 'GI'},
  {'name': 'Indonesia', 'shortName': 'ID'},
  {'name': 'Pitcairn Islands', 'shortName': 'PN'},
  {'name': 'Vietnam', 'shortName': 'VN'},
  {'name': 'Malaysia', 'shortName': 'MY'},
  {'name': 'Cook Islands', 'shortName': 'CK'},
  {'name': 'Eswatini', 'shortName': 'SZ'},
  {'name': 'Uganda', 'shortName': 'UG'},
  {'name': 'Madagascar', 'shortName': 'MG'},
  {'name': 'Fiji', 'shortName': 'FJ'},
  {'name': 'Norway', 'shortName': 'NO'},
  {'name': 'Antarctica', 'shortName': 'AQ'},
  {'name': 'Bouvet Island', 'shortName': 'BV'},
  {'name': 'Cyprus', 'shortName': 'CY'},
  {'name': 'Taiwan', 'shortName': 'TW'},
  {'name': 'Papua New Guinea', 'shortName': 'PG'},
  {'name': 'Rwanda', 'shortName': 'RW'},
  {'name': 'DR Congo', 'shortName': 'CD'},
  {'name': 'Cameroon', 'shortName': 'CM'},
  {'name': 'Serbia', 'shortName': 'RS'},
  {'name': 'Lithuania', 'shortName': 'LT'},
  {'name': 'French Southern and Antarctic Lands', 'shortName': 'TF'},
  {'name': 'Cambodia', 'shortName': 'KH'},
  {'name': 'Saint Helena', 'shortName': 'SH'},
  {'name': 'United Arab Emirates', 'shortName': 'AE'},
  {'name': 'Bermuda', 'shortName': 'BM'},
  {'name': 'Monaco', 'shortName': 'MC'},
  {'name': 'Cuba', 'shortName': 'CU'},
  {'name': 'Hong Kong', 'shortName': 'HK'},
  {'name': 'Northern Mariana Islands', 'shortName': 'MP'},
  {'name': 'Togo', 'shortName': 'TG'},
  {'name': 'Luxembourg', 'shortName': 'LU'},
  {'name': 'Mauritius', 'shortName': 'MU'},
  {'name': 'Argentina', 'shortName': 'AR'},
  {'name': 'Grenada', 'shortName': 'GD'},
  {'name': 'Nicaragua', 'shortName': 'NI'},
  {'name': 'Niue', 'shortName': 'NU'},
  {'name': 'Ukraine', 'shortName': 'UA'},
  {'name': 'Guyana', 'shortName': 'GY'},
  {'name': 'Niger', 'shortName': 'NE'},
  {'name': 'Benin', 'shortName': 'BJ'},
  {'name': 'Saint Lucia', 'shortName': 'LC'},
  {'name': 'Tuvalu', 'shortName': 'TV'},
  {'name': 'Norfolk Island', 'shortName': 'NF'},
  {'name': 'Egypt', 'shortName': 'EG'},
  {'name': 'Saint Kitts and Nevis', 'shortName': 'KN'},
  {'name': 'Lesotho', 'shortName': 'LS'},
  {'name': 'Tonga', 'shortName': 'TO'},
  {'name': 'Georgia', 'shortName': 'GE'},
  {'name': 'Ethiopia', 'shortName': 'ET'},
  {'name': 'Dominican Republic', 'shortName': 'DO'},
  {'name': 'Saint Vincent', 'shortName': 'VC'},
  {'name': 'Belize', 'shortName': 'BZ'},
  {'name': 'Isle of Man', 'shortName': 'IM'},
  {'name': 'Morocco', 'shortName': 'MA'},
  {'name': 'Haiti', 'shortName': 'HT'},
  {'name': 'Mayotte', 'shortName': 'YT'},
  {'name': 'Burkina Faso', 'shortName': 'BF'},
  {'name': 'Bangladesh', 'shortName': 'BD'},
  {'name': 'Kuwait', 'shortName': 'KW'},
  {'name': 'RÃunion', 'shortName': 'RE'},
  {'name': 'Jamaica', 'shortName': 'JM'},
  {'name': 'Romania', 'shortName': 'RO'},
  {'name': 'SÃ£o TomÃ and PrÃ­ncipe', 'shortName': 'ST'},
  {'name': 'Bahamas', 'shortName': 'BS'},
  {'name': 'Mexico', 'shortName': 'MX'},
  {'name': 'Saint Martin', 'shortName': 'MF'},
  {'name': 'El Salvador', 'shortName': 'SV'},
  {'name': 'Saint BarthÃ©lemy', 'shortName': 'BL'},
  {'name': 'Micronesia', 'shortName': 'FM'},
  {'name': 'Turkmenistan', 'shortName': 'TM'},
  {'name': 'Anguilla', 'shortName': 'AI'},
  {'name': 'Central African Republic', 'shortName': 'CF'},
  {'name': 'Suriname', 'shortName': 'SR'},
  {'name': 'Belgium', 'shortName': 'BE'},
  {'name': 'Sweden', 'shortName': 'SE'},
  {'name': 'Bolivia', 'shortName': 'BO'},
  {'name': 'Montenegro', 'shortName': 'ME'},
  {'name': 'Mozambique', 'shortName': 'MZ'},
  {'name': 'Latvia', 'shortName': 'LV'},
  {'name': 'Malawi', 'shortName': 'MW'},
  {'name': 'Mali', 'shortName': 'ML'},
  {'name': 'Vatican City', 'shortName': 'VA'},
  {'name': 'Montserrat', 'shortName': 'MS'},
  {'name': 'Austria', 'shortName': 'AT'},
  {'name': 'Albania', 'shortName': 'AL'},
  {'name': 'British Virgin Islands', 'shortName': 'VG'},
  {'name': 'Zambia', 'shortName': 'ZM'},
  {'name': 'French Guiana', 'shortName': 'GF'},
  {'name': 'Liechtenstein', 'shortName': 'LI'},
  {'name': 'Qatar', 'shortName': 'QA'},
  {'name': 'Solomon Islands', 'shortName': 'SB'},
  {'name': 'Nauru', 'shortName': 'NR'},
  {'name': 'Greece', 'shortName': 'GR'},
  {'name': 'Libya', 'shortName': 'LY'},
  {'name': 'Guinea-Bissau', 'shortName': 'GW'},
  {'name': 'Barbados', 'shortName': 'BB'},
  {'name': 'Honduras', 'shortName': 'HN'},
  {'name': 'Somalia', 'shortName': 'SO'},
  {'name': 'Cayman Islands', 'shortName': 'KY'},
  {'name': 'Italy', 'shortName': 'IT'},
  {'name': 'Wallis and Futuna', 'shortName': 'WF'},
  {'name': 'Andorra', 'shortName': 'AD'},
  {'name': 'Ecuador', 'shortName': 'EC'},
  {'name': 'Kenya', 'shortName': 'KE'},
  {'name': 'Bahrain', 'shortName': 'BH'},
  {'name': 'United Kingdom', 'shortName': 'GB'},
  {'name': 'Guinea', 'shortName': 'GN'},
  {'name': 'Heard Island and McDonald Islands', 'shortName': 'HM'},
  {'name': 'Russia', 'shortName': 'RU'},
  {'name': 'Brunei', 'shortName': 'BN'},
  {'name': 'Zimbabwe', 'shortName': 'ZW'},
  {'name': 'Guam', 'shortName': 'GU'},
  {'name': 'Australia', 'shortName': 'AU'},
  {'name': 'Slovenia', 'shortName': 'SI'},
  {'name': 'Belarus', 'shortName': 'BY'},
  {'name': 'Thailand', 'shortName': 'TH'},
  {'name': 'New Zealand', 'shortName': 'NZ'},
  {'name': 'Tunisia', 'shortName': 'TN'},
  {'name': 'Marshall Islands', 'shortName': 'MH'},
  {'name': 'Sierra Leone', 'shortName': 'SL'},
  {'name': 'Bhutan', 'shortName': 'BT'},
  {'name': 'United States', 'shortName': 'US'},
  {'name': 'Switzerland', 'shortName': 'CH'},
  {'name': 'Falkland Islands', 'shortName': 'FK'},
  {'name': 'Cocos (Keeling) Islands', 'shortName': 'CC'},
  {'name': 'Gabon', 'shortName': 'GA'},
  {'name': 'Dominica', 'shortName': 'DM'},
  {'name': 'Canada', 'shortName': 'CA'},
  {'name': 'Trinidad and Tobago', 'shortName': 'TT'},
  {'name': 'Puerto Rico', 'shortName': 'PR'},
  {'name': 'Singapore', 'shortName': 'SG'},
  {'name': 'Hungary', 'shortName': 'HU'},
  {'name': 'Costa Rica', 'shortName': 'CR'},
  {'name': 'Israel', 'shortName': 'IL'},
  {'name': 'Bulgaria', 'shortName': 'BG'},
  {'name': 'Azerbaijan', 'shortName': 'AZ'},
  {'name': 'Timor-Leste', 'shortName': 'TL'},
  {'name': 'Iran', 'shortName': 'IR'},
  {'name': 'Croatia', 'shortName': 'HR'},
  {'name': 'Ivory Coast', 'shortName': 'CI'}
];
